version: '3'
services:
  sdc_5:
    build: .
    image: loyzious/sdc_5_streamlit_ml_fastapi:v.0.1.0
    ports:
      #- '8000:8000'
      #- '8501:8501'
      - 80:${STREAMLIT_SERVER_PORT:-80}
    environment:
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-80}
