version: '3'
services:
  sdc_5:
    build: .
    image: loyzious/sdc_5_streamlit_ml_fastapi:latest
    ports:
      #- '8000:8000'
      #- '8501:8501'
      - 80:${STREAMLIT_SERVER_PORT:-80}
      - 8000:${FASTAPI_SERVER_PORT:-8000}
    environment:
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-80}
      - FASTAPI_SERVER_PORT=${FASTAPI_SERVER_PORT:-8000}
