# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ds21m001-sdc5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b696a990db8b406ebb3f2ab6f7b3f91a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4b36a3c24c7149deb68d2e0d3c22dd59 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b696a990db8b406ebb3f2ab6f7b3f91a }}/sdc_5_streamlit_ml_fastapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ds21m001-sdc5'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4c7d1fdf648944469c1d8a2b0222e419 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b696a990db8b406ebb3f2ab6f7b3f91a }}/sdc_5_streamlit_ml_fastapi:${{ github.sha }}'